/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace pointofsale.cloud.doordash.Model
{
    /// <summary>
    /// NestedItemExtraOption
    /// </summary>
    [DataContract]
    public class NestedItemExtraOption :  IEquatable<NestedItemExtraOption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NestedItemExtraOption" /> class.
        /// </summary>
        [JsonConstructor]
        protected NestedItemExtraOption() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NestedItemExtraOption" /> class.
        /// </summary>
        /// <param name="name">the given name of this instance (required).</param>
        /// <param name="description">description.</param>
        /// <param name="merchantSuppliedId">ID as it&#39;s stored in your system.</param>
        /// <param name="active">active (default to true).</param>
        /// <param name="price">price (required).</param>
        /// <param name="basePrice">basePrice.</param>
        /// <param name="_default">_default.</param>
        /// <param name="sortId">sortId.</param>
        /// <param name="taxRate">taxRate.</param>
        /// <param name="extras">extras.</param>
        public NestedItemExtraOption(string name = default(string), string description = default(string), string merchantSuppliedId = default(string), bool? active = true, int? price = default(int?), int? basePrice = default(int?), bool? _default = default(bool?), int? sortId = default(int?), string taxRate = default(string), List<NestedL2ItemExtra> extras = default(List<NestedL2ItemExtra>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for NestedItemExtraOption and cannot be null");
            }
            else
            {
                Name = name;
            }
            // to ensure "price" is required (not null)
            if (price == null)
            {
                throw new InvalidDataException("price is a required property for NestedItemExtraOption and cannot be null");
            }
            else
            {
                Price = price;
            }
            Description = description;
            MerchantSuppliedId = merchantSuppliedId;
            // use default value if no "active" provided
            if (active == null)
            {
                Active = true;
            }
            else
            {
                Active = active;
            }
            BasePrice = basePrice;
            Default = _default;
            SortId = sortId;
            TaxRate = taxRate;
            Extras = extras;
        }
        
        /// <summary>
        /// the given name of this instance
        /// </summary>
        /// <value>the given name of this instance</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// ID as it&#39;s stored in your system
        /// </summary>
        /// <value>ID as it&#39;s stored in your system</value>
        [DataMember(Name="merchant_supplied_id", EmitDefaultValue=false)]
        public string MerchantSuppliedId { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name="active", EmitDefaultValue=false)]
        public bool? Active { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public int? Price { get; set; }

        /// <summary>
        /// Gets or Sets BasePrice
        /// </summary>
        [DataMember(Name="base_price", EmitDefaultValue=false)]
        public int? BasePrice { get; set; }

        /// <summary>
        /// Gets or Sets Default
        /// </summary>
        [DataMember(Name="default", EmitDefaultValue=false)]
        public bool? Default { get; set; }

        /// <summary>
        /// Gets or Sets SortId
        /// </summary>
        [DataMember(Name="sort_id", EmitDefaultValue=false)]
        public int? SortId { get; set; }

        /// <summary>
        /// Gets or Sets TaxRate
        /// </summary>
        [DataMember(Name="tax_rate", EmitDefaultValue=false)]
        public string TaxRate { get; set; }

        /// <summary>
        /// Gets or Sets Extras
        /// </summary>
        [DataMember(Name="extras", EmitDefaultValue=false)]
        public List<NestedL2ItemExtra> Extras { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NestedItemExtraOption {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MerchantSuppliedId: ").Append(MerchantSuppliedId).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  BasePrice: ").Append(BasePrice).Append("\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("  SortId: ").Append(SortId).Append("\n");
            sb.Append("  TaxRate: ").Append(TaxRate).Append("\n");
            sb.Append("  Extras: ").Append(Extras).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as NestedItemExtraOption);
        }

        /// <summary>
        /// Returns true if NestedItemExtraOption instances are equal
        /// </summary>
        /// <param name="input">Instance of NestedItemExtraOption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NestedItemExtraOption input)
        {
            if (input == null)
                return false;

            return 
                (
                    Name == input.Name ||
                    Name != null &&
                    Name.Equals(input.Name)
                ) && 
                (
                    Description == input.Description ||
                    Description != null &&
                    Description.Equals(input.Description)
                ) && 
                (
                    MerchantSuppliedId == input.MerchantSuppliedId ||
                    MerchantSuppliedId != null &&
                    MerchantSuppliedId.Equals(input.MerchantSuppliedId)
                ) && 
                (
                    Active == input.Active ||
                    Active != null &&
                    Active.Equals(input.Active)
                ) && 
                (
                    Price == input.Price ||
                    Price != null &&
                    Price.Equals(input.Price)
                ) && 
                (
                    BasePrice == input.BasePrice ||
                    BasePrice != null &&
                    BasePrice.Equals(input.BasePrice)
                ) && 
                (
                    Default == input.Default ||
                    Default != null &&
                    Default.Equals(input.Default)
                ) && 
                (
                    SortId == input.SortId ||
                    SortId != null &&
                    SortId.Equals(input.SortId)
                ) && 
                (
                    TaxRate == input.TaxRate ||
                    TaxRate != null &&
                    TaxRate.Equals(input.TaxRate)
                ) && 
                (
                    Extras == input.Extras ||
                    Extras != null &&
                    Extras.SequenceEqual(input.Extras)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                if (MerchantSuppliedId != null)
                    hashCode = hashCode * 59 + MerchantSuppliedId.GetHashCode();
                if (Active != null)
                    hashCode = hashCode * 59 + Active.GetHashCode();
                if (Price != null)
                    hashCode = hashCode * 59 + Price.GetHashCode();
                if (BasePrice != null)
                    hashCode = hashCode * 59 + BasePrice.GetHashCode();
                if (Default != null)
                    hashCode = hashCode * 59 + Default.GetHashCode();
                if (SortId != null)
                    hashCode = hashCode * 59 + SortId.GetHashCode();
                if (TaxRate != null)
                    hashCode = hashCode * 59 + TaxRate.GetHashCode();
                if (Extras != null)
                    hashCode = hashCode * 59 + Extras.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
