/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing Item
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemTests
    {
        // TODO uncomment below to declare an instance variable for Item
        //private Item instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Item
            //instance = new Item();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Item
        /// </summary>
        [Test]
        public void ItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Item
            //Assert.IsInstanceOfType<Item> (instance, "variable 'instance' is a Item");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'IsAlcohol'
        /// </summary>
        [Test]
        public void IsAlcoholTest()
        {
            // TODO unit test for the property 'IsAlcohol'
        }
        /// <summary>
        /// Test the property 'IsBikeFriendly'
        /// </summary>
        [Test]
        public void IsBikeFriendlyTest()
        {
            // TODO unit test for the property 'IsBikeFriendly'
        }
        /// <summary>
        /// Test the property 'SortId'
        /// </summary>
        [Test]
        public void SortIdTest()
        {
            // TODO unit test for the property 'SortId'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Test]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }
        /// <summary>
        /// Test the property 'Extras'
        /// </summary>
        [Test]
        public void ExtrasTest()
        {
            // TODO unit test for the property 'Extras'
        }
        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Test]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }
        /// <summary>
        /// Test the property 'OriginalImageUrl'
        /// </summary>
        [Test]
        public void OriginalImageUrlTest()
        {
            // TODO unit test for the property 'OriginalImageUrl'
        }

    }

}
