/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing MenuDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MenuDetailsTests
    {
        // TODO uncomment below to declare an instance variable for MenuDetails
        //private MenuDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MenuDetails
            //instance = new MenuDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MenuDetails
        /// </summary>
        [Test]
        public void MenuDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MenuDetails
            //Assert.IsInstanceOfType<MenuDetails> (instance, "variable 'instance' is a MenuDetails");
        }


        /// <summary>
        /// Test the property 'MenuId'
        /// </summary>
        [Test]
        public void MenuIdTest()
        {
            // TODO unit test for the property 'MenuId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Subtitle'
        /// </summary>
        [Test]
        public void SubtitleTest()
        {
            // TODO unit test for the property 'Subtitle'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsPosMenu'
        /// </summary>
        [Test]
        public void IsPosMenuTest()
        {
            // TODO unit test for the property 'IsPosMenu'
        }
        /// <summary>
        /// Test the property 'LatestMenuUpdate'
        /// </summary>
        [Test]
        public void LatestMenuUpdateTest()
        {
            // TODO unit test for the property 'LatestMenuUpdate'
        }
        /// <summary>
        /// Test the property 'LastSuccessfulMenuUpdateAt'
        /// </summary>
        [Test]
        public void LastSuccessfulMenuUpdateAtTest()
        {
            // TODO unit test for the property 'LastSuccessfulMenuUpdateAt'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'OpenHours'
        /// </summary>
        [Test]
        public void OpenHoursTest()
        {
            // TODO unit test for the property 'OpenHours'
        }
        /// <summary>
        /// Test the property 'SpecialHours'
        /// </summary>
        [Test]
        public void SpecialHoursTest()
        {
            // TODO unit test for the property 'SpecialHours'
        }

    }

}
