/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing Menu
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MenuTests
    {
        // TODO uncomment below to declare an instance variable for Menu
        //private Menu instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Menu
            //instance = new Menu();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Menu
        /// </summary>
        [Test]
        public void MenuInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Menu
            //Assert.IsInstanceOfType<Menu> (instance, "variable 'instance' is a Menu");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Subtitle'
        /// </summary>
        [Test]
        public void SubtitleTest()
        {
            // TODO unit test for the property 'Subtitle'
        }
        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }

    }

}
