/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing MerchantOrderRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MerchantOrderRecordTests
    {
        // TODO uncomment below to declare an instance variable for MerchantOrderRecord
        //private MerchantOrderRecord instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchantOrderRecord
            //instance = new MerchantOrderRecord();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchantOrderRecord
        /// </summary>
        [Test]
        public void MerchantOrderRecordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MerchantOrderRecord
            //Assert.IsInstanceOfType<MerchantOrderRecord> (instance, "variable 'instance' is a MerchantOrderRecord");
        }


        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'OrderStatus'
        /// </summary>
        [Test]
        public void OrderStatusTest()
        {
            // TODO unit test for the property 'OrderStatus'
        }
        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Test]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }
        /// <summary>
        /// Test the property 'PrepTime'
        /// </summary>
        [Test]
        public void PrepTimeTest()
        {
            // TODO unit test for the property 'PrepTime'
        }

    }

}
