/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing NestedL2ItemExtra
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NestedL2ItemExtraTests
    {
        // TODO uncomment below to declare an instance variable for NestedL2ItemExtra
        //private NestedL2ItemExtra instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NestedL2ItemExtra
            //instance = new NestedL2ItemExtra();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NestedL2ItemExtra
        /// </summary>
        [Test]
        public void NestedL2ItemExtraInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NestedL2ItemExtra
            //Assert.IsInstanceOfType<NestedL2ItemExtra> (instance, "variable 'instance' is a NestedL2ItemExtra");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'SortId'
        /// </summary>
        [Test]
        public void SortIdTest()
        {
            // TODO unit test for the property 'SortId'
        }
        /// <summary>
        /// Test the property 'MinNumOptions'
        /// </summary>
        [Test]
        public void MinNumOptionsTest()
        {
            // TODO unit test for the property 'MinNumOptions'
        }
        /// <summary>
        /// Test the property 'MaxNumOptions'
        /// </summary>
        [Test]
        public void MaxNumOptionsTest()
        {
            // TODO unit test for the property 'MaxNumOptions'
        }
        /// <summary>
        /// Test the property 'NumFreeOptions'
        /// </summary>
        [Test]
        public void NumFreeOptionsTest()
        {
            // TODO unit test for the property 'NumFreeOptions'
        }
        /// <summary>
        /// Test the property 'MinOptionChoiceQuantity'
        /// </summary>
        [Test]
        public void MinOptionChoiceQuantityTest()
        {
            // TODO unit test for the property 'MinOptionChoiceQuantity'
        }
        /// <summary>
        /// Test the property 'MaxOptionChoiceQuantity'
        /// </summary>
        [Test]
        public void MaxOptionChoiceQuantityTest()
        {
            // TODO unit test for the property 'MaxOptionChoiceQuantity'
        }
        /// <summary>
        /// Test the property 'MinAggregateOptionsQuantity'
        /// </summary>
        [Test]
        public void MinAggregateOptionsQuantityTest()
        {
            // TODO unit test for the property 'MinAggregateOptionsQuantity'
        }
        /// <summary>
        /// Test the property 'MaxAggregateOptionsQuantity'
        /// </summary>
        [Test]
        public void MaxAggregateOptionsQuantityTest()
        {
            // TODO unit test for the property 'MaxAggregateOptionsQuantity'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
