/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing NestedOrderItemExtraOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NestedOrderItemExtraOptionTests
    {
        // TODO uncomment below to declare an instance variable for NestedOrderItemExtraOption
        //private NestedOrderItemExtraOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NestedOrderItemExtraOption
            //instance = new NestedOrderItemExtraOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NestedOrderItemExtraOption
        /// </summary>
        [Test]
        public void NestedOrderItemExtraOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NestedOrderItemExtraOption
            //Assert.IsInstanceOfType<NestedOrderItemExtraOption> (instance, "variable 'instance' is a NestedOrderItemExtraOption");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
