/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing Order
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderTests
    {
        // TODO uncomment below to declare an instance variable for Order
        //private Order instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Order
            //instance = new Order();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Order
        /// </summary>
        [Test]
        public void OrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Order
            //Assert.IsInstanceOfType<Order> (instance, "variable 'instance' is a Order");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Consumer'
        /// </summary>
        [Test]
        public void ConsumerTest()
        {
            // TODO unit test for the property 'Consumer'
        }
        /// <summary>
        /// Test the property 'Store'
        /// </summary>
        [Test]
        public void StoreTest()
        {
            // TODO unit test for the property 'Store'
        }
        /// <summary>
        /// Test the property 'Subtotal'
        /// </summary>
        [Test]
        public void SubtotalTest()
        {
            // TODO unit test for the property 'Subtotal'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'EstimatedPickupTime'
        /// </summary>
        [Test]
        public void EstimatedPickupTimeTest()
        {
            // TODO unit test for the property 'EstimatedPickupTime'
        }
        /// <summary>
        /// Test the property 'IsPickup'
        /// </summary>
        [Test]
        public void IsPickupTest()
        {
            // TODO unit test for the property 'IsPickup'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'IsTaxRemittedByDoordash'
        /// </summary>
        [Test]
        public void IsTaxRemittedByDoordashTest()
        {
            // TODO unit test for the property 'IsTaxRemittedByDoordash'
        }
        /// <summary>
        /// Test the property 'TaxAmountRemittedByDoordash'
        /// </summary>
        [Test]
        public void TaxAmountRemittedByDoordashTest()
        {
            // TODO unit test for the property 'TaxAmountRemittedByDoordash'
        }
        /// <summary>
        /// Test the property 'CommissionType'
        /// </summary>
        [Test]
        public void CommissionTypeTest()
        {
            // TODO unit test for the property 'CommissionType'
        }
        /// <summary>
        /// Test the property 'DeliveryShortCode'
        /// </summary>
        [Test]
        public void DeliveryShortCodeTest()
        {
            // TODO unit test for the property 'DeliveryShortCode'
        }

    }

}
