/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing StoreMenuInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreMenuInfoTests
    {
        // TODO uncomment below to declare an instance variable for StoreMenuInfo
        //private StoreMenuInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreMenuInfo
            //instance = new StoreMenuInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreMenuInfo
        /// </summary>
        [Test]
        public void StoreMenuInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreMenuInfo
            //Assert.IsInstanceOfType<StoreMenuInfo> (instance, "variable 'instance' is a StoreMenuInfo");
        }


        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Test]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }
        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'Menus'
        /// </summary>
        [Test]
        public void MenusTest()
        {
            // TODO unit test for the property 'Menus'
        }

    }

}
