/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing StoreInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreInfoTests
    {
        // TODO uncomment below to declare an instance variable for StoreInfo
        //private StoreInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreInfo
            //instance = new StoreInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreInfo
        /// </summary>
        [Test]
        public void StoreInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreInfo
            //Assert.IsInstanceOfType<StoreInfo> (instance, "variable 'instance' is a StoreInfo");
        }


        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Test]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }
        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsOrderProtocolPos'
        /// </summary>
        [Test]
        public void IsOrderProtocolPosTest()
        {
            // TODO unit test for the property 'IsOrderProtocolPos'
        }
        /// <summary>
        /// Test the property 'AutoReleaseEnabled'
        /// </summary>
        [Test]
        public void AutoReleaseEnabledTest()
        {
            // TODO unit test for the property 'AutoReleaseEnabled'
        }
        /// <summary>
        /// Test the property 'AutoReleaseDistance'
        /// </summary>
        [Test]
        public void AutoReleaseDistanceTest()
        {
            // TODO unit test for the property 'AutoReleaseDistance'
        }
        /// <summary>
        /// Test the property 'SpecialInstructionsMaxLength'
        /// </summary>
        [Test]
        public void SpecialInstructionsMaxLengthTest()
        {
            // TODO unit test for the property 'SpecialInstructionsMaxLength'
        }
        /// <summary>
        /// Test the property 'CurrentDeactivations'
        /// </summary>
        [Test]
        public void CurrentDeactivationsTest()
        {
            // TODO unit test for the property 'CurrentDeactivations'
        }

    }

}
