/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing StoreMenu
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreMenuTests
    {
        // TODO uncomment below to declare an instance variable for StoreMenu
        //private StoreMenu instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreMenu
            //instance = new StoreMenu();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreMenu
        /// </summary>
        [Test]
        public void StoreMenuInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreMenu
            //Assert.IsInstanceOfType<StoreMenu> (instance, "variable 'instance' is a StoreMenu");
        }


        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Store'
        /// </summary>
        [Test]
        public void StoreTest()
        {
            // TODO unit test for the property 'Store'
        }
        /// <summary>
        /// Test the property 'OpenHours'
        /// </summary>
        [Test]
        public void OpenHoursTest()
        {
            // TODO unit test for the property 'OpenHours'
        }
        /// <summary>
        /// Test the property 'SpecialHours'
        /// </summary>
        [Test]
        public void SpecialHoursTest()
        {
            // TODO unit test for the property 'SpecialHours'
        }
        /// <summary>
        /// Test the property 'Menu'
        /// </summary>
        [Test]
        public void MenuTest()
        {
            // TODO unit test for the property 'Menu'
        }

    }

}
