/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing Store
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreTests
    {
        // TODO uncomment below to declare an instance variable for Store
        //private Store instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Store
            //instance = new Store();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Store
        /// </summary>
        [Test]
        public void StoreInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Store
            //Assert.IsInstanceOfType<Store> (instance, "variable 'instance' is a Store");
        }


        /// <summary>
        /// Test the property 'MerchantSuppliedId'
        /// </summary>
        [Test]
        public void MerchantSuppliedIdTest()
        {
            // TODO unit test for the property 'MerchantSuppliedId'
        }
        /// <summary>
        /// Test the property 'ProviderType'
        /// </summary>
        [Test]
        public void ProviderTypeTest()
        {
            // TODO unit test for the property 'ProviderType'
        }

    }

}
