/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing StoreSpecialHour
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreSpecialHourTests
    {
        // TODO uncomment below to declare an instance variable for StoreSpecialHour
        //private StoreSpecialHour instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreSpecialHour
            //instance = new StoreSpecialHour();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreSpecialHour
        /// </summary>
        [Test]
        public void StoreSpecialHourInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreSpecialHour
            //Assert.IsInstanceOfType<StoreSpecialHour> (instance, "variable 'instance' is a StoreSpecialHour");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Closed'
        /// </summary>
        [Test]
        public void ClosedTest()
        {
            // TODO unit test for the property 'Closed'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

    }

}
