/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing StoreOpenHour
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreOpenHourTests
    {
        // TODO uncomment below to declare an instance variable for StoreOpenHour
        //private StoreOpenHour instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreOpenHour
            //instance = new StoreOpenHour();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreOpenHour
        /// </summary>
        [Test]
        public void StoreOpenHourInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreOpenHour
            //Assert.IsInstanceOfType<StoreOpenHour> (instance, "variable 'instance' is a StoreOpenHour");
        }


        /// <summary>
        /// Test the property 'DayIndex'
        /// </summary>
        [Test]
        public void DayIndexTest()
        {
            // TODO unit test for the property 'DayIndex'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

    }

}
