/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace pointofsale.cloud.doordash.test.Model
{
    /// <summary>
    ///  Class for testing StoreActivationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreActivationStatusTests
    {
        // TODO uncomment below to declare an instance variable for StoreActivationStatus
        //private StoreActivationStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreActivationStatus
            //instance = new StoreActivationStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreActivationStatus
        /// </summary>
        [Test]
        public void StoreActivationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreActivationStatus
            //Assert.IsInstanceOfType<StoreActivationStatus> (instance, "variable 'instance' is a StoreActivationStatus");
        }


        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ShouldSendEmail'
        /// </summary>
        [Test]
        public void ShouldSendEmailTest()
        {
            // TODO unit test for the property 'ShouldSendEmail'
        }

    }

}
