/*
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;
using pointofsale.cloud.doordash.Api;

namespace pointofsale.cloud.doordash.test.Api
{
    /// <summary>
    ///  Class for testing Apiv1ordersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class Apiv1ordersApiTests
    {
        private OrdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiv1ordersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Apiv1ordersApi
            //Assert.IsInstanceOfType(typeof(Apiv1ordersApi), instance, "instance is a Apiv1ordersApi");
        }


        /// <summary>
        /// Test PatchOrderDetailView
        /// </summary>
        [Test]
        public void PatchOrderDetailViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //MerchantOrderRecord payload = null;
            //instance.PatchOrderDetailView(id, payload);

        }

    }

}