/*
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;
using pointofsale.cloud.doordash.Api;

namespace pointofsale.cloud.doordash.test.Api
{
    /// <summary>
    ///  Class for testing Apiv1menusApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class Apiv1MenusApiTests
    {
        MenusApi _instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            _instance = new MenusApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiv1menusApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Apiv1menusApi
            //Assert.IsInstanceOfType(typeof(Apiv1menusApi), instance, "instance is a Apiv1menusApi");
        }


        /// <summary>
        /// Test PatchMenuDetailView
        /// </summary>
        [Test]
        public void PatchMenuDetailViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string userAgent = null;
            //string authorization = null;
            //instance.PatchMenuDetailView(id, userAgent, authorization);

        }

        /// <summary>
        /// Test PostMenuListView
        /// </summary>
        [Test]
        public void PostMenuListViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StoreMenu payload = null;
            //string userAgent = null;
            //string authorization = null;
            //instance.PostMenuListView(payload, userAgent, authorization);

        }

    }

}